version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 16-bullseye
    command: sleep infinity

    volumes:
      - ..:/workspace:cached
    env_file:
      - .env
    network_mode: host

  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    network_mode: host

volumes:
  postgres-data: null
